### ISSUE TITLE
Symfony 3.0.6 not working at all - All the relation mapping lost while using original entity

### ISSUE THREAD

**Issue by sagaraspl** [joschi127/doctrine-entity-override-bundle#4]
Hi @joschi127 

I have tested this today and it is now even worse then previous version. In older version only Many-Many now not working. Now it stopped working for all the relations. One-One, One-Many, Many-One and so on... Nothing is working with version 0.4.3.

After overwriting entity relation not working while saving the data

E.g.

If I have USER entity at vendor level and It has many to many with roles and after using your bundle and overwriting the USER entity at application level, when loading fixture using doctrine fixture the addRole method not saving data into many to many relation when trying to save using source entity. Though it is working when using overwritten entity but it Many to Many relation should also work with base or source entity. Suppose I am putting following...

joschi127_doctrine_entity_override:
overridden_entities:
Fa\Bundle\UserBundle\Entity\User: App\Bundle\UserBundle\Entity\User

Then it should work with Fa\Bundle\UserBundle\Entity\User as well.

**Comment by joschi127** [comment]
Hi,

Is your class Fa\Bundle\UserBundle\Entity\User extending the Mapped Super Class FOS\UserBundle\Model\User? 

If yes,  then you have to use the key FOS\UserBundle\Model\User in your Config. Your Config should look like this:

joschi127_doctrine_entity_override:
overridden_entities:
FOS\UserBundle\Model\User: App\Bundle\UserBundle\Entity\User

I have already added a comment about this in the Readme because it won't work if you do not use the top most Superclass in the Config. 

It might as well be necessary to have the properties of your class Fa\Bundle\UserBundle\Entity\User be declared protected, not private. 

You can also compare your own project with the Tests of this bundle here: https://github.com/joschi127/doctrine-entity-override-bundle/blob/master/Tests/ 
You can find the Config for the Tests here:
https://github.com/joschi127/doctrine-entity-override-bundle/blob/master/Tests/Functional/app/config/config.yml

I hope it works this time for you ;-) I think you are almost there now....

**Comment by sagaraspl** [comment]
Hi @joschi127 

I have used your code in following way.

joschi127_doctrine_entity_override:
    overridden_entities:
        # Keep in mind: if you are using multi level inheritance, you have to use the top most super class on the
        # left side
        Fa\Bundle\UserBundle\Entity\User: App\Bundle\UserBundle\Entity\User

I am not using FosUserBundle, we have our custom code. This is my own entity class. 
Fa\Bundle\UserBundle\Entity\User.

I haven't used FosUserBundle nor used mapped supper class. I also have all properties in this class Fa\Bundle\UserBundle\Entity\User already declared as protected.

The issue is that I have code written with Fa\Bundle\UserBundle\Entity\User at vendor level and If I will use your overwritten the older code should work as it is where I have used for e.g.

$user = new Fa\Bundle\UserBundle\Entity\User();
$user->setStatus(status object); relation // not working
$user->addRole(role boject); relation // not working
$user->setFirstName('sagar'); working 
$em->persist($user);
$em->flush();

Though it is working with following

$user = new App\Bundle\UserBundle\Entity\User();
$user->setStatus(status object); relation // working
$user->addRole(role boject); relation // working
$user->setFirstName('sagar'); working 
$em->persist($user);
$em->flush();

But I want everything to be working with both 

$user = new Fa\Bundle\UserBundle\Entity\User();
$user = new App\Bundle\UserBundle\Entity\User();

So you can see that relation fields not working at all while saving using left side or original class.

It is not necessary that I should follow the strategy used by FosUserBundle

**Comment by joschi127** [comment]
Okay... yes, that's another problem. You cannot use a hard coded new Fa\Bundle\UserBundle\Entity\User(); because it will always create an object of the wrong class for you. There is also no way to tell PHP not to do so. 

You have to use something like a manager service for this. So that you can use something like this in your code:

$user = $userManager->createUser();

Or maybe also:

$user = $genericManager->create("Fa\Bundle\UserBundle\Entity\User");

However a manager like this is not part of this bundle. You have to write your own. 

Maybe I find some time later to add something generic to this bundle as well but I do not know yet. 

I hope I could help you! 

Thanks for your feedback!

**Comment by sagaraspl** [comment]
Hi @joschi127 

Yes I have created customer factory which will give me correct object at run time and it seems that it is working now. Though I will test more.

**Comment by sagaraspl** [comment]
Hi @joschi127 

This is work at certain places but this is actually a bigger change in existing system, consider suppose I am overwriting user table then I have to replace the reference at all the places where I have used User as reference which is really not good solution. Consider for e.g. I have table advert and I have reference of User.

/**
     \* @var \Fa\Bundle\UserBundle\Entity\User
     *
     \* @ORM\ManyToOne(targetEntity="Fa\Bundle\UserBundle\Entity\User")
     \* @ORM\JoinColumns({
     \*   @ORM\JoinColumn(name="user_id", referencedColumnName="id", onDelete="CASCADE", nullable=true)
     \* })
     */
    private $user;

So I have to change at each and every place where I have used this class as reference which is really not good. Even factory solution won't work in this case because we have written code in annotation and can't detect and apply class at run time in those places.

**Comment by joschi127** [comment]
I'm not sure... But if you define your original Entity as MappedSuperClass instead of as Entity this should work. You should then be able to keep other Associations directly to Fa\Bundle\UserBundle\Entity\User, even if you have overridden it.

I can try this as well and add some additional tests and example implementation for things like that. But it will still take some time, I do not know yet when I will be able to find the time.

**Comment by sagaraspl** [comment]
Hi @joschi127 

I have tried with all different possibilities but it seems that it faces the issue when comes to namespace and doesn't work with any kind of combination and not even with supper class.

**Comment by joschi127** [comment]
Hi @sagaraspl,

as far as I understand, your final issue was that it did not work when you were using other entities with relations to the customized entity.

For example a relation like

    @ORM\ManyToOne(targetEntity="Fa\Bundle\UserBundle\Entity\User")

from the example code you've posted above was failing, because the User entity which was given as targetEntit in the mapping was customized.

If my understanding is correct, then this was now addressed in #6 and should from now on be fixed by https://github.com/joschi127/doctrine-entity-override-bundle/pull/7. The fix was merged into master a few minutes ago.

Hope it solves your issue as well.

**Comment by joschi127** [comment]
No feedback anymore. Issue should be fixed by #7  .
So closing this now.
